version: '3.1'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    volumes:
      - .:/app
    networks:
      - networkreact

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react-app
    networks:
      - networkreact

networks:
  networkreact:
    driver: bridge
