version: '3.1'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - react-app-data:/usr/share/nginx/html
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    volumes:
      - react-app-data:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - react-app

volumes:
  react-app-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${EFS_DNS_NAME},nfsvers=4"
      device: ":/"
